import type { Content } from '@/lib/types';

export const allContent: Content[] = [
  // Birthday - Enhanced with more quotes
  {
    id: 1,
    categorySlug: 'birthday',
    text: 'Wishing you a day filled with happiness and a year filled with joy. Happy birthday!',
    author: 'Badmus',
    tags: ['happy', 'joyful'],
    length: 'short',
    popularity: 95,
  },
  {
    id: 2,
    categorySlug: 'birthday',
    text: 'May your birthday be the start of a year filled with good luck, good health, and much happiness.',
    author: 'Badmus',
    tags: ['happy', 'blessing'],
    length: 'short',
    popularity: 88,
  },
  {
    id: 3,
    categorySlug: 'birthday',
    text: "Count your life by smiles, not tears. Count your age by friends, not years. Happy birthday!",
    author: 'John Lennon',
    tags: ['inspirational', 'friendship'],
    length: 'short',
    popularity: 98,
  },
  {
    id: 4,
    categorySlug: 'birthday',
    text: "Another adventure-filled year awaits you. Welcome it by celebrating your birthday with pomp and splendor. Wishing you a very happy and fun-filled birthday!",
    author: 'Badmus',
    tags: ['adventurous', 'celebration'],
    length: 'medium',
    popularity: 85,
  },
  {
    id: 5,
    categorySlug: 'birthday',
    text: "On your birthday, I wish for you that whatever you want most in life comes to you just the way you imagined it or better. Happy birthday!",
    author: 'Badmus',
    tags: ['wishes', 'inspirational'],
    length: 'medium',
    popularity: 91,
  },
  {
    id: 6,
    categorySlug: 'birthday',
    text: "May your birthday be the beginning of a year filled with good luck, good health, and much happiness.",
    author: 'Badmus',
    tags: ['blessing', 'joy'],
    length: 'short',
    popularity: 89,
  },
  {
    id: 7,
    categorySlug: 'birthday',
    text: "Sending you smiles for every moment of your special day. Have a wonderful time and a very happy birthday!",
    author: 'Badmus',
    tags: ['happy', 'celebration'],
    length: 'medium',
    popularity: 87,
  },
  {
    id: 8,
    categorySlug: 'birthday',
    text: "Another year older, another year wiser, another year more amazing. Happy birthday to someone who keeps getting better with age!",
    author: 'Badmus',
    tags: ['funny', 'age'],
    length: 'long',
    popularity: 90,
  },
  {
    id: 9,
    categorySlug: 'birthday',
    text: "May your birthday be filled with the warmth of sunshine, the happiness of smiles, the sounds of laughter, the feeling of love, and the enjoyment of good food. Happy birthday!",
    author: 'Badmus',
    tags: ['celebration', 'joy'],
    length: 'long',
    popularity: 94,
  },
  {
    id: 10,
    categorySlug: 'birthday',
    text: "Happy birthday to someone who is forever young!",
    author: 'Badmus',
    tags: ['short', 'sweet'],
    length: 'short',
    popularity: 85,
  },

  // Love & Romance - Enhanced with more quotes
  {
    id: 11,
    categorySlug: 'love-romance',
    text: 'You are my sun, my moon, and all my stars.',
    author: 'E.E. Cummings',
    tags: ['romantic', 'poetic'],
    length: 'short',
    popularity: 99,
  },
  {
    id: 12,
    categorySlug: 'love-romance',
    text: 'If I know what love is, it is because of you.',
    author: 'Hermann Hesse',
    tags: ['romantic', 'deep'],
    length: 'short',
    popularity: 96,
  },
  {
    id: 13,
    categorySlug: 'love-romance',
    text: "I love you not only for what you are, but for what I am when I am with you.",
    author: 'Roy Croft',
    tags: ['romantic', 'inspirational'],
    length: 'medium',
    popularity: 97,
  },
  {
    id: 14,
    categorySlug: 'love-romance',
    text: "To the world you may be one person, but to one person you are the world.",
    author: 'Dr. Seuss',
    tags: ['romantic', 'sweet'],
    length: 'short',
    popularity: 93,
  },
  {
    id: 15,
    categorySlug: 'love-romance',
    text: "My heart is and always will be yours.",
    author: 'Jane Austen',
    tags: ['classic', 'romantic'],
    length: 'short',
    popularity: 92,
  },
  {
    id: 16,
    categorySlug: 'love-romance',
    text: "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
    author: 'Maya Angelou',
    tags: ['romantic', 'poetic'],
    length: 'medium',
    popularity: 95,
  },
  {
    id: 17,
    categorySlug: 'love-romance',
    text: "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.",
    author: 'Angelita Lim',
    tags: ['romantic', 'unconditional'],
    length: 'medium',
    popularity: 94,
  },
  {
    id: 18,
    categorySlug: 'love-romance',
    text: "You're my favorite notification in a day full of messages.",
    author: 'Badmus',
    tags: ['modern', 'sweet'],
    length: 'short',
    popularity: 90,
  },
  {
    id: 19,
    categorySlug: 'love-romance',
    text: "I love you more than I have ever found a way to say to you.",
    author: 'Ben Folds',
    tags: ['romantic', 'deep'],
    length: 'short',
    popularity: 91,
  },
  {
    id: 20,
    categorySlug: 'love-romance',
    text: "I love you as certain dark things are to be loved, in secret, between the shadow and the soul.",
    author: 'Pablo Neruda',
    tags: ['poetic', 'romantic'],
    length: 'medium',
    popularity: 96,
  },

  // Heartbreak & Healing
  {
    id: 21,
    categorySlug: 'heartbreak-healing',
    text: "The heart was made to be broken.",
    author: 'Oscar Wilde',
    tags: ['heartbreak', 'wisdom'],
    length: 'short',
    popularity: 88,
  },
  {
    id: 22,
    categorySlug: 'heartbreak-healing',
    text: "Tears are words that need to be written.",
    author: 'Paulo Coelho',
    tags: ['healing', 'emotional'],
    length: 'short',
    popularity: 85,
  },
  {
    id: 23,
    categorySlug: 'heartbreak-healing',
    text: "The wound is the place where the Light enters you.",
    author: 'Rumi',
    tags: ['healing', 'inspirational'],
    length: 'short',
    popularity: 92,
  },
  {
    id: 24,
    categorySlug: 'heartbreak-healing',
    text: "It's okay to be sad. It's okay to cry. But know that you will smile again.",
    author: 'Badmus',
    tags: ['comfort', 'hope'],
    length: 'medium',
    popularity: 90,
  },
  {
    id: 25,
    categorySlug: 'heartbreak-healing',
    text: "The best way to heal a broken heart is time and friends.",
    author: 'Badmus',
    tags: ['healing', 'friendship'],
    length: 'short',
    popularity: 87,
  },
  {
    id: 26,
    categorySlug: 'heartbreak-healing',
    text: "Don't cry because it's over, smile because it happened.",
    author: 'Dr. Seuss',
    tags: ['moving on', 'positive'],
    length: 'short',
    popularity: 94,
  },
  {
    id: 27,
    categorySlug: 'heartbreak-healing',
    text: "The pain you feel today is the strength you feel tomorrow.",
    author: 'Badmus',
    tags: ['strength', 'growth'],
    length: 'short',
    popularity: 89,
  },
  {
    id: 28,
    categorySlug: 'heartbreak-healing',
    text: "Healing is an art. It takes time, it takes practice, it takes love.",
    author: 'Maza Dohta',
    tags: ['healing', 'process'],
    length: 'medium',
    popularity: 86,
  },
  {
    id: 29,
    categorySlug: 'heartbreak-healing',
    text: "The only way out of the labyrinth of suffering is to forgive.",
    author: 'John Green',
    tags: ['forgiveness', 'healing'],
    length: 'medium',
    popularity: 91,
  },
  {
    id: 30,
    categorySlug: 'heartbreak-healing',
    text: "You cannot heal in the same environment that made you sick.",
    author: 'Unknown',
    tags: ['wisdom', 'healing'],
    length: 'short',
    popularity: 93,
  },
  {
    id: 12,
    categorySlug: 'heartbreak-healing',
    text: "It's okay to not be okay. It's okay to fall apart. Just pick yourself up, piece by piece, and start again.",
    author: 'Unknown',
    tags: ['healing', 'hopeful'],
    length: 'medium',
    popularity: 89,
  },
  {
    id: 13,
    categorySlug: 'heartbreak-healing',
    text: "Sometimes, you have to let go to see if there was anything worth holding on to.",
    author: 'Unknown',
    tags: ['letting go', 'sad'],
    length: 'medium',
    popularity: 90,
  },
  {
    id: 14,
    categorySlug: 'heartbreak-healing',
    text: "Pain makes you stronger, fear makes you braver, heartbreak makes you wiser.",
    author: 'Unknown',
    tags: ['strength', 'inspirational'],
    length: 'short',
    popularity: 92,
  },
  {
    id: 15,
    categorySlug: 'heartbreak-healing',
    text: "New beginnings are often disguised as painful endings.",
    author: 'Lao Tzu',
    tags: ['hopeful', 'inspirational'],
    length: 'short',
    popularity: 95,
  },

  // Inspirational & Motivational
  {
    id: 50,
    categorySlug: 'inspirational-motivational',
    text: "Believe you can and you're halfway there.",
    author: 'Theodore Roosevelt',
    tags: ['motivation', 'success'],
    length: 'short',
    popularity: 97,
  },
  {
    id: 51,
    categorySlug: 'inspirational-motivational',
    text: "The only way to do great work is to love what you do.",
    author: 'Steve Jobs',
    tags: ['passion', 'success'],
    length: 'short',
    popularity: 98,
  },
  {
    id: 52,
    categorySlug: 'inspirational-motivational',
    text: "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    author: 'Winston Churchill',
    tags: ['perseverance', 'success'],
    length: 'medium',
    popularity: 96,
  },
  {
    id: 53,
    categorySlug: 'inspirational-motivational',
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: 'Eleanor Roosevelt',
    tags: ['dreams', 'aspiration'],
    length: 'medium',
    popularity: 95,
  },
  {
    id: 54,
    categorySlug: 'inspirational-motivational',
    text: "Don't watch the clock; do what it does. Keep going.",
    author: 'Sam Levenson',
    tags: ['perseverance', 'focus'],
    length: 'short',
    popularity: 92,
  },
  {
    id: 55,
    categorySlug: 'inspirational-motivational',
    text: "The only limit to our realization of tomorrow is our doubts of today.",
    author: 'Franklin D. Roosevelt',
    tags: ['positivity', 'future'],
    length: 'medium',
    popularity: 94,
  },
  {
    id: 56,
    categorySlug: 'inspirational-motivational',
    text: "Your time is limited, don't waste it living someone else's life.",
    author: 'Steve Jobs',
    tags: ['authenticity', 'wisdom'],
    length: 'medium',
    popularity: 96,
  },
  {
    id: 57,
    categorySlug: 'inspirational-motivational',
    text: "The only person you are destined to become is the person you decide to be.",
    author: 'Ralph Waldo Emerson',
    tags: ['self-improvement', 'destiny'],
    length: 'medium',
    popularity: 93,
  },
  {
    id: 58,
    categorySlug: 'inspirational-motivational',
    text: "Everything you've ever wanted is on the other side of fear.",
    author: 'George Addair',
    tags: ['courage', 'overcoming fear'],
    length: 'short',
    popularity: 95,
  },
  {
    id: 59,
    categorySlug: 'inspirational-motivational',
    text: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    author: 'Albert Schweitzer',
    tags: ['happiness', 'success'],
    length: 'long',
    popularity: 97,
  },
  {
    id: 16,
    categorySlug: 'inspirational-motivational',
    text: 'Believe you can and you’re halfway there.',
    author: 'Theodore Roosevelt',
    tags: ['belief', 'motivation'],
    length: 'short',
    popularity: 99,
  },
  {
    id: 17,
    categorySlug: 'inspirational-motivational',
    text: 'The only way to do great work is to love what you do.',
    author: 'Steve Jobs',
    tags: ['work', 'passion'],
    length: 'short',
    popularity: 98,
  },
  {
    id: 18,
    categorySlug: 'inspirational-motivational',
    text: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    author: 'Winston Churchill',
    tags: ['courage', 'success'],
    length: 'medium',
    popularity: 97,
  },
  {
    id: 19,
    categorySlug: 'inspirational-motivational',
    text: "The future belongs to those who believe in the beauty of their dreams.",
    author: 'Eleanor Roosevelt',
    tags: ['dreams', 'future'],
    length: 'medium',
    popularity: 96,
  },
  {
    id: 20,
    categorySlug: 'inspirational-motivational',
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: 'Confucius',
    tags: ['perseverance', 'motivation'],
    length: 'short',
    popularity: 95,
  },
  
  // Holiday Greetings
  {
    id: 21,
    categorySlug: 'holiday-greetings',
    text: "Wishing you a magical and blissful holiday! Have a merry Christmas and a prosperous New Year!",
    author: 'Unknown',
    tags: ['christmas', 'new year'],
    length: 'short',
    popularity: 90,
  },
  {
    id: 22,
    categorySlug: 'holiday-greetings',
    text: "May this season be full of light and laughter for you and your family.",
    author: 'Unknown',
    tags: ['family', 'festive'],
    length: 'short',
    popularity: 88,
  },

  // Life Milestones
  {
    id: 23,
    categorySlug: 'life-milestones',
    text: "Congratulations on your graduation! The future is all yours. Shine on!",
    author: 'Unknown',
    tags: ['graduation', 'congratulations'],
    length: 'short',
    popularity: 92,
  },
  {
    id: 24,
    categorySlug: 'life-milestones',
    text: "Wishing you a lifetime of love and happiness. Congratulations on your wedding!",
    author: 'Unknown',
    tags: ['wedding', 'love'],
    length: 'short',
    popularity: 94,
  },
  {
    id: 25,
    categorySlug: 'life-milestones',
    text: "Cheers to your new job! May it bring you joy, challenges, and success.",
    author: 'Unknown',
    tags: ['new job', 'success'],
    length: 'short',
    popularity: 89,
  },

  // Friendship & Family
  {
    id: 26,
    categorySlug: 'friendship-family',
    text: "A friend is one who knows you and loves you just the same.",
    author: 'Elbert Hubbard',
    tags: ['friendship', 'love'],
    length: 'short',
    popularity: 96,
  },
  {
    id: 27,
    categorySlug: 'friendship-family',
    text: "Family is not an important thing. It's everything.",
    author: 'Michael J. Fox',
    tags: ['family', 'inspirational'],
    length: 'short',
    popularity: 97,
  },
  
  // Daily Affirmations
  {
    id: 28,
    categorySlug: 'daily-affirmations',
    text: "I am capable of achieving my dreams.",
    author: 'Self',
    tags: ['confidence', 'positive'],
    length: 'short',
    popularity: 85,
  },
  {
    id: 29,
    categorySlug: 'daily-affirmations',
    text: "I choose to be happy and to love myself today.",
    author: 'Self',
    tags: ['self-love', 'happiness'],
    length: 'short',
    popularity: 88,
  },

  // Sympathy & Support
  {
    id: 30,
    categorySlug: 'sympathy-support',
    text: "Thinking of you and wishing you moments of peace and comfort.",
    author: 'Unknown',
    tags: ['comfort', 'support'],
    length: 'short',
    popularity: 91,
  },
  {
    id: 31,
    categorySlug: 'sympathy-support',
    text: "May you find strength in the love of family and in the warm embrace of friends.",
    author: 'Unknown',
    tags: ['strength', 'friendship'],
    length: 'medium',
    popularity: 90,
  },
  
  // Poems
  {
    id: 32,
    categorySlug: 'poems',
    text: "The woods are lovely, dark and deep, \nBut I have promises to keep, \nAnd miles to go before I sleep, \nAnd miles to go before I sleep.",
    author: 'Robert Frost',
    tags: ['classic', 'journey'],
    length: 'long',
    popularity: 95,
  },
  
  // Social Media Captions
  {
    id: 33,
    categorySlug: 'social-media-captions',
    text: "Creating my own sunshine.",
    author: 'Unknown',
    tags: ['positive', 'selfie'],
    length: 'short',
    popularity: 87,
  },
  {
    id: 34,
    categorySlug: 'social-media-captions',
    text: "Chasing sunsets and dreams.",
    author: 'Unknown',
    tags: ['travel', 'dreams'],
    length: 'short',
    popularity: 90,
  },
  
  // Monthly Celebrations
  {
    id: 35,
    categorySlug: 'monthly-celebrations',
    text: "Hello January! A fresh start to make new memories.",
    author: 'Unknown',
    tags: ['january', 'new beginnings'],
    length: 'short',
    popularity: 80,
  },
  {
    id: 36,
    categorySlug: 'monthly-celebrations',
    text: "Welcome December! May your days be merry and bright.",
    author: 'Unknown',
    tags: ['december', 'festive'],
    length: 'short',
    popularity: 86,
  },
];


export const getContentByCategory = (categorySlug: string) => {
  return allContent.filter((item) => item.categorySlug === categorySlug);
};

export const getContentById = (id: number) => {
  return allContent.find((item) => item.id === id);
}

export const getTrendingContent = (limit: number = 5) => {
    return [...allContent].sort((a, b) => b.popularity - a.popularity).slice(0, limit);
}

export const getQuoteOfTheDay = () => {
    // Simple logic: return a fixed quote.
    // A better approach would be to use the date to pick a daily quote.
    return allContent[15];
}
